#!/usr/bin/env python3
"""policy_lint.py — Flag the common failure modes in a syllabus AI-use policy.

Reads a Markdown AI-use policy (e.g. the output of policy_builder.py, or a draft
the instructor pasted) and reports the failure modes that make such policies
unenforceable. STDLIB ONLY; no network, no keys.

Checks (see ../references/ for the rationale):
  vague-catch-all   A blanket "use AI responsibly"-style line with no per-task tier.
  no-tier           No prohibited/restricted/permitted tier wording found at all.
  missing-disclosure A restricted/permitted tier appears but no disclosure clause.
  vague-citation    "cite appropriately"-style instruction with no concrete template.
  unresolved-code   The integrity-code reference is missing or still a placeholder.
  contradiction     The same task line is tagged both prohibited and permitted.

Severity: 'error' findings cause a non-zero exit (so this can gate a check);
'warning' findings are advisory. Use --json for machine-readable output.

Usage:
  uv run python policy_lint.py ai_policy.md
  uv run python policy_lint.py - < ai_policy.md      # read stdin
  uv run python policy_lint.py ai_policy.md --json

Exit codes: 0 = no error-level findings; 1 = >=1 error finding; 2 = bad usage.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import asdict, dataclass

TIER_WORDS = ("prohibited", "restricted", "permitted")

# A blanket permission with no structure — the single most common failure.
VAGUE_CATCH_ALL = re.compile(
    r"\buse\s+(?:generative\s+)?ai\s+responsibly\b"
    r"|\bmay\s+use\s+ai\s+as\s+(?:they|you)\s+see\s+fit\b"
    r"|\bAI\s+is\s+allowed\s+throughout\b",
    re.IGNORECASE,
)

VAGUE_CITATION = re.compile(
    r"\bcite\s+(?:it\s+)?appropriately\b"
    r"|\bcite\s+as\s+(?:needed|appropriate)\b"
    r"|\bproper(?:ly)?\s+cite\b(?![^.]*OpenAI)",
    re.IGNORECASE,
)

# Concrete citation template present? (any of these signals one)
CONCRETE_CITATION = re.compile(
    r"OpenAI\.\s*\(\d{4}(?:,\s*[A-Za-z]+\s+\d{1,2})?\)"  # APA author-date
    r"|\[(?:Large language model|Generative AI chat)\]"  # APA descriptions
    r"|prompt\.\s*\*?(?:ChatGPT|<Tool>)"  # MLA container form
    r"|Text generated by",  # Chicago note form
    re.IGNORECASE,
)

DISCLOSURE_SIGNAL = re.compile(
    r"\bdisclos", re.IGNORECASE
)

CODE_PLACEHOLDER = re.compile(r"<CODE_REF>")
INTEGRITY_SIGNAL = re.compile(
    r"academic[- ]integrity|integrity\s+violation|handled\s+under", re.IGNORECASE
)


@dataclass
class Finding:
    code: str
    severity: str  # "error" | "warning"
    message: str


def assigned_tiers(text: str) -> set[str]:
    """Tiers actually ASSIGNED to a task, read from bold tokens in table rows.

    Mirrors the contradiction check: a tier only counts when it appears as a
    bold ``**Prohibited**`` / ``**Restricted**`` / ``**Permitted**`` token inside
    a Markdown table row. This keeps disclosure-clause and integrity-binding
    boilerplate — which always names "Restricted" and "Permitted" in prose —
    from being mistaken for a tier assignment.
    """
    tiers: set[str] = set()
    for raw in text.splitlines():
        line = raw.strip()
        if not line.startswith("|"):
            continue
        low = line.lower()
        for w in TIER_WORDS:
            if f"**{w}**" in low:
                tiers.add(w)
    return tiers


def lint(text: str) -> list[Finding]:
    findings: list[Finding] = []

    tiers_present = sorted(assigned_tiers(text))
    has_restricted_or_permitted = bool(
        {"restricted", "permitted"} & set(tiers_present)
    )

    # no-tier
    if not tiers_present:
        findings.append(
            Finding(
                "no-tier",
                "error",
                "No prohibited/restricted/permitted tier wording found — the "
                "policy assigns no per-task tier.",
            )
        )

    # vague-catch-all (only an error when it stands in for tiers)
    if VAGUE_CATCH_ALL.search(text):
        sev = "error" if len(tiers_present) == 0 else "warning"
        findings.append(
            Finding(
                "vague-catch-all",
                sev,
                "Found a blanket 'use AI responsibly'-style line. Replace with an "
                "explicit per-task tier (default-deny when unstated).",
            )
        )

    # missing-disclosure
    if has_restricted_or_permitted and not DISCLOSURE_SIGNAL.search(text):
        findings.append(
            Finding(
                "missing-disclosure",
                "error",
                "A Restricted/Permitted tier is used but no disclosure clause was "
                "found. Restricted/Permitted tasks must require disclosure.",
            )
        )

    # vague-citation
    if VAGUE_CITATION.search(text) and not CONCRETE_CITATION.search(text):
        findings.append(
            Finding(
                "vague-citation",
                "error",
                "Citation instruction is vague ('cite appropriately') with no "
                "concrete template (APA/MLA/Chicago). Supply the exact format.",
            )
        )
    elif has_restricted_or_permitted and not CONCRETE_CITATION.search(text):
        findings.append(
            Finding(
                "vague-citation",
                "warning",
                "Restricted/Permitted tier present but no concrete citation "
                "template detected. Add the APA/MLA/Chicago AI-citation form.",
            )
        )

    # unresolved-code
    if CODE_PLACEHOLDER.search(text):
        findings.append(
            Finding(
                "unresolved-code",
                "error",
                "Integrity-code reference is still the <CODE_REF> placeholder. "
                "Insert the institution's academic-integrity code.",
            )
        )
    elif not INTEGRITY_SIGNAL.search(text):
        findings.append(
            Finding(
                "unresolved-code",
                "warning",
                "No academic-integrity binding sentence found. Tie prohibited-tier "
                "misuse to the named institutional code.",
            )
        )

    # contradiction: a single assignment tagged BOTH prohibited and permitted.
    # Only inspect Markdown table rows (an assignment + its tier), so the
    # integrity-binding sentence — which legitimately names several tiers — and
    # legend rows are not false-positives. A genuine clash needs two *assignment*
    # tiers, which we detect as bold tokens (**Prohibited** / **Permitted**).
    for raw in text.splitlines():
        line = raw.strip()
        if not line.startswith("|"):
            continue
        low = line.lower()
        if "**prohibited**" in low and "**permitted**" in low:
            findings.append(
                Finding(
                    "contradiction",
                    "error",
                    f"A table row tags the same assignment both Prohibited and "
                    f"Permitted: {line[:120]!r}",
                )
            )

    return findings


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description="Flag common failure modes in a syllabus AI-use policy."
    )
    p.add_argument("path", help="Markdown policy file, or '-' for stdin")
    p.add_argument("--json", action="store_true", help="Emit findings as JSON")
    args = p.parse_args(argv)

    if args.path == "-":
        text = sys.stdin.read()
    else:
        try:
            with open(args.path, encoding="utf-8") as fh:
                text = fh.read()
        except OSError as exc:
            print(f"error: cannot read {args.path}: {exc}", file=sys.stderr)
            return 2

    findings = lint(text)
    errors = [f for f in findings if f.severity == "error"]

    if args.json:
        print(
            json.dumps(
                {
                    "path": args.path,
                    "verdict": "FAIL" if errors else "PASS",
                    "error_count": len(errors),
                    "findings": [asdict(f) for f in findings],
                },
                indent=2,
            )
        )
    else:
        if not findings:
            print("PASS — no findings.")
        else:
            for f in findings:
                print(f"[{f.severity.upper():7}] {f.code:18} {f.message}")
            print(
                f"\n{'FAIL' if errors else 'PASS'} — "
                f"{len(errors)} error(s), "
                f"{len(findings) - len(errors)} warning(s)."
            )

    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
