#!/usr/bin/env python3
"""policy_builder.py — Emit a paste-ready syllabus generative-AI use statement.

Given a course and a list of graded tasks (each tagged with a tier), this fills
local Markdown templates to produce an enforceable AI-use policy: a per-task
tier table, a disclosure + citation clause keyed to the course's documentation
standard, and integrity / accessibility language bound to the institution's own
academic-integrity code.

Design constraints (mirrors alterlab-citation-verifier's house style):
- STDLIB ONLY. No network, no API keys, no third-party deps.
- ZERO FABRICATION. The script never invents an integrity-code reference, a tool
  capability, a version string, or a citation URL. Anything the user did not
  supply is emitted as a visible ``<PLACEHOLDER>`` and reported.
- DEFAULT-DENY. A task given no tier is emitted as ``prohibited`` with a
  "instructor to confirm" note — never a silent "responsible use".

Tiers: prohibited | restricted | permitted  (see ../references/tier_framework.md)

Citation templates follow current published style guidance (APA Style blog
"Citing generative AI in APA Style", September 2025; MLA Style Center "How do I
cite generative AI in MLA style? (Updated and Revised)", August 2025). See
../references/disclosure_and_citation.md for sources.

Usage:
  uv run python policy_builder.py --course "PSY 201" --level undergraduate \\
      --doc-standard apa --integrity-code "IEU Student Disciplinary Regulation" \\
      --task "Essay=restricted:brainstorming only" \\
      --task "Final exam=prohibited" \\
      --task "Code report=permitted:as a coding tutor" \\
      --out ai_policy.md

  uv run python policy_builder.py --course "..." --task "..."   # prints to stdout

Exit codes: 0 = statement emitted (see trailing "Unresolved placeholders" note);
            2 = bad usage / unknown tier.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass

CODE_PLACEHOLDER = "<CODE_REF>"
TIERS = ("prohibited", "restricted", "permitted")

# --------------------------------------------------------------------------- #
# Citation templates — VERBATIM from published style guidance. Do not edit the #
# wording without re-checking the source cited in disclosure_and_citation.md.  #
# --------------------------------------------------------------------------- #

CITATION_BLOCKS = {
    "apa": (
        "**Citing AI (APA 7).** The author is the company that made the tool, not "
        "the tool or yourself. When a chat produced ideas, content, or information "
        "you used, cite that specific chat (use the tool's share link):\n\n"
        "> <Company>. (<Year, Month Day>). *<Title of chat>* [Generative AI chat]. "
        "<Tool/model>. <Share-link URL>\n\n"
        "For general use of a tool (for example, editing your own writing), cite "
        "the tool:\n\n"
        "> OpenAI. (2025). *ChatGPT* (GPT-5) [Large language model]. https://chatgpt.com/\n\n"
        "In-text: `(<Company>, <Year>)`, e.g. `(OpenAI, 2025)`. Replace the "
        "company, date, title, model, and link with the ones you actually used."
    ),
    "mla": (
        "**Citing AI (MLA 9).** Treat the tool as the container, not the author, "
        "and name the model in the version element:\n\n"
        "> \"<Description of prompt>\" prompt. *<Tool>*, model <model name>, "
        "<Company>, <date generated>, <shareable chat URL, or the tool's general "
        "URL if it has no share link>.\n\n"
        "Also acknowledge functional uses (editing, translation) in a note even "
        "when nothing is quoted."
    ),
    "chicago": (
        "**Citing AI (Chicago, note).** Disclose AI use in a note (confirm wording "
        "against the Chicago Manual of Style Online before publishing):\n\n"
        "> 1. Text generated by <Tool>, <Company>, <date>, <URL>."
    ),
    "none": (
        "**Citing AI.** Cite any AI use in the documentation standard this course "
        "uses; see your instructor for the required format."
    ),
}

DISCLOSURE_CLAUSE = (
    "**Disclosure.** For any task marked *Restricted* or *Permitted*, attach an "
    "AI-Use Declaration stating (1) which tool and version, (2) for which "
    "sub-tasks, (3) how you verified the output (AI can fabricate facts and "
    "citations), and (4) the citation in the format below. You remain "
    "responsible for the accuracy of anything an AI tool produced."
)

TIER_INTENT = {
    "prohibited": "No generative-AI use. This task measures a skill AI would "
    "substitute for; AI use is an integrity violation under the cited code.",
    "restricted": "Generative AI is permitted for the NAMED sub-tasks only, never "
    "for the assessed deliverable. Disclose and cite any use.",
    "permitted": "Generative-AI use is allowed (and may be encouraged). Disclose "
    "and cite per the template; you remain responsible for accuracy.",
}


@dataclass
class Task:
    name: str
    tier: str
    scope: str = ""
    confirm: bool = False  # True when tier was defaulted (instructor to confirm)


def parse_task(spec: str) -> Task:
    """Parse "Name=tier:scope" / "Name=tier" / "Name" (-> default-deny)."""
    if "=" not in spec:
        return Task(name=spec.strip(), tier="prohibited", confirm=True)
    name, rhs = spec.split("=", 1)
    name = name.strip()
    if not name:
        raise SystemExit(f"error: task spec has empty name: {spec!r}")
    if ":" in rhs:
        tier, scope = rhs.split(":", 1)
    else:
        tier, scope = rhs, ""
    tier = tier.strip().lower()
    if tier not in TIERS:
        raise SystemExit(
            f"error: unknown tier {tier!r} for task {name!r}; "
            f"use one of {', '.join(TIERS)}"
        )
    return Task(name=name, tier=tier, scope=scope.strip())


def build(args: argparse.Namespace) -> tuple[str, list[str]]:
    """Return (markdown_statement, unresolved_placeholders)."""
    placeholders: list[str] = []
    tasks = [parse_task(t) for t in args.task]

    code = args.integrity_code.strip() if args.integrity_code else CODE_PLACEHOLDER
    if code == CODE_PLACEHOLDER:
        placeholders.append(
            f"{CODE_PLACEHOLDER} — no institutional academic-integrity code "
            "supplied; fill in before publishing."
        )

    out: list[str] = []
    out.append(f"## Generative-AI Use Policy — {args.course}")
    out.append("")
    out.append(
        f"_Level: {args.level}. This policy assigns every graded task an explicit "
        "AI-use tier. A task not listed here is **Prohibited** until the "
        "instructor states otherwise._"
    )
    out.append("")

    # Per-task tier table
    out.append("### Per-assignment tiers")
    out.append("")
    out.append("| Assignment | Tier | What this means |")
    out.append("|------------|------|-----------------|")
    for t in tasks:
        intent = TIER_INTENT[t.tier]
        if t.scope:
            intent += f" Allowed sub-tasks: {t.scope}."
        if t.confirm:
            intent += (
                " _(No tier was specified; defaulted to Prohibited — "
                "instructor to confirm.)_"
            )
            placeholders.append(
                f"Tier for '{t.name}' defaulted to Prohibited — confirm."
            )
        out.append(f"| {t.name} | **{t.tier.capitalize()}** | {intent} |")
    out.append("")

    # Disclosure + citation
    out.append("### Disclosure and citation")
    out.append("")
    out.append(DISCLOSURE_CLAUSE)
    out.append("")
    out.append(CITATION_BLOCKS[args.doc_standard])
    out.append("")

    # Integrity binding
    out.append("### Academic integrity")
    out.append("")
    out.append(
        f"Use of generative AI on a *Prohibited* task, or undisclosed use on a "
        f"*Restricted* or *Permitted* task, is an academic-integrity violation "
        f"and is handled under {code}."
    )
    out.append("")

    # Accessibility / equity
    out.append("### Accessibility and equity")
    out.append("")
    out.append(
        "Documented assistive use of AI-backed tools as a disability "
        "accommodation is permitted and is not an integrity concern. Where a task "
        "requires AI use, it is achievable on a free tier or institutional access "
        "is provided. Generative AI can fabricate facts and citations; you remain "
        "responsible for verifying any AI-assisted output."
    )
    out.append("")

    return "\n".join(out).rstrip() + "\n", placeholders


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description="Emit a paste-ready syllabus generative-AI use statement.",
    )
    p.add_argument("--course", required=True, help="Course code/title, e.g. 'PSY 201'")
    p.add_argument(
        "--level",
        default="undergraduate",
        help="Course level (free text), e.g. undergraduate, graduate",
    )
    p.add_argument(
        "--doc-standard",
        default="apa",
        choices=sorted(CITATION_BLOCKS),
        help="Documentation standard for the AI-citation template",
    )
    p.add_argument(
        "--integrity-code",
        default="",
        help="Verbatim reference to the institution's academic-integrity code. "
        "Omit and a visible <CODE_REF> placeholder is emitted.",
    )
    p.add_argument(
        "--task",
        action="append",
        default=[],
        metavar="NAME=TIER[:SCOPE]",
        help="Repeatable. tier in {prohibited,restricted,permitted}. "
        "'NAME' alone defaults to prohibited (instructor to confirm).",
    )
    p.add_argument("--out", help="Write Markdown here; omit to print to stdout")
    args = p.parse_args(argv)

    if not args.task:
        p.error("at least one --task is required")

    statement, placeholders = build(args)

    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(statement)
        print(f"Wrote policy to {args.out}", file=sys.stderr)
    else:
        sys.stdout.write(statement)

    if placeholders:
        print("\nUnresolved placeholders (resolve before publishing):", file=sys.stderr)
        for ph in placeholders:
            print(f"  - {ph}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
